# Generated by Django 3.2.4 on 2021-06-11 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('head', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='page.people')),
            ],
            options={
                'ordering': ('-date_time',),
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='page.people')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('on_duty', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=9)),
                ('phone', models.CharField(max_length=11)),
                ('e_mail', models.CharField(max_length=50)),
                ('name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='page.people')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
