# Generated by Django 3.2.4 on 2021-06-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_contacts_members_orders_people_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
