# Generated by Django 3.2.4 on 2021-06-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210611_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='publish',
        ),
    ]
