# Generated by Django 3.2.4 on 2021-06-11 17:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210611_1944'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
