# Generated by Django 3.2.4 on 2021-06-11 18:15

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20210611_2041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='auto_increment_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
