# Generated by Django 3.2.4 on 2021-06-11 18:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_order_auto_increment_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
