# Generated by Django 3.2.4 on 2021-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20210611_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoView',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='photo')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
