# Generated by Django 3.2.4 on 2021-06-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_photoview_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='photoview',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
